import React, { useState, useEffect } from 'react';
import SecretsManager from './SecretsManager';
import WorkflowSearch from './WorkflowSearch';
import AIWorkflowAnalysis from './AIWorkflowAnalysis';
import TemplatesManager from './TemplatesManager';
import LegacyConfigCleanup from './LegacyConfigCleanup';
import { useRequiredSecrets } from './useRequiredSecrets';
import './index.css';

function App() {
  const [activeTab, setActiveTab] = useState('workflow-search'); // 'secrets', 'workflow-search', 'ai-analysis', 'templates', or 'legacy-cleanup'
  const { loading, allConfigured, hasGitHubToken, tokenIsEmpty, isAutoGenerated, recheckSecrets } = useRequiredSecrets();
  const [showConfigModal, setShowConfigModal] = useState(false);
  const [appVersion, setAppVersion] = useState('');


  useEffect(() => {
    // Show modal if secrets are not configured
    if (!loading && !allConfigured) {
      setShowConfigModal(true);
    }
  }, [loading, allConfigured]);

  useEffect(() => {
    // Fetch app version
    fetch('/api/version')
      .then(res => res.json())
      .then(data => setAppVersion(data.version))
      .catch(err => console.error('Failed to fetch version:', err));
  }, []);

  const handleGoToSecrets = () => {
    setShowConfigModal(false);
    setActiveTab('secrets');
  };

  return (
    <div className="App">
      <header className="header">
        <h1>GitHub Onboarding Tool</h1>
        <p>Manage GitHub organizations, repositories, and workflows</p>
      </header>

      {/* Navigation Tabs */}
      <div className="nav-tabs">
        <button
          className={`nav-tab ${activeTab === 'workflow-search' ? 'active' : ''}`}
          onClick={() => setActiveTab('workflow-search')}
        >
          🔍 Workflow Search
        </button>
        <button 
          className={`nav-tab ${activeTab === 'ai-analysis' ? 'active' : ''}`}
          onClick={() => setActiveTab('ai-analysis')}
        >
          🤖 AI Workflow Analysis
        </button>
        <button 
          className={`nav-tab ${activeTab === 'templates' ? 'active' : ''}`}
          onClick={() => setActiveTab('templates')}
        >
          📄 Templates
        </button>
        <button 
          className={`nav-tab ${activeTab === 'legacy-cleanup' ? 'active' : ''}`}
          onClick={() => setActiveTab('legacy-cleanup')}
        >
          🧹 Legacy Cleanup
        </button>
        <button 
          className={`nav-tab ${activeTab === 'secrets' ? 'active' : ''}`}
          onClick={() => setActiveTab('secrets')}
        >
          🔐 Secrets Management
        </button>
      </div>

      {/* Required Secrets Configuration Modal */}
      {showConfigModal && (
        <div className="modal-overlay">
          <div className="config-modal">
            <div className="modal-header">
              <h2>{isAutoGenerated ? '🔧 Configuration Needed' : '⚠️ Configuration Required'}</h2>
            </div>
            <div className="modal-body">
              {isAutoGenerated ? (
                <>
                  <div className="auto-generated-notice">
                    <p><strong>✓ Required secrets have been automatically created!</strong></p>
                    <p>However, they need your attention:</p>
                  </div>
                  <ul className="missing-list">
                    {tokenIsEmpty && (
                      <li>
                        <span className="missing-icon">⚠️</span>
                        <strong>GITHUB_TOKEN</strong> - Currently empty. Add your Personal Access Token from <a href="https://github.com/settings/tokens" target="_blank" rel="noopener noreferrer">GitHub Settings</a>
                      </li>
                    )}
                  </ul>
                </>
              ) : (
                <>
                  <p>The following required secrets need to be configured:</p>
                  <ul className="missing-list">
                    {!hasGitHubToken && (
                      <li>
                        <span className="missing-icon">❌</span>
                        <strong>GITHUB_TOKEN</strong> - Your GitHub Personal Access Token
                      </li>
                    )}
                  </ul>
                </>
              )}
              <div className="modal-info">
                <p>These secrets are required for the application to function properly. Please {isAutoGenerated ? 'review and update' : 'configure'} them in the Secrets Management section.</p>
              </div>
            </div>
            <div className="modal-footer">
              <button onClick={handleGoToSecrets} className="primary-btn">
                {isAutoGenerated ? 'Review Secrets' : 'Go to Secrets Management'}
              </button>
              <button onClick={() => setShowConfigModal(false)} className="secondary-btn">
                {isAutoGenerated ? 'I\'ll Check Later' : 'Remind Me Later'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Conditional Rendering based on active tab */}
      {activeTab === 'secrets' ? (
        <SecretsManager onSecretsUpdated={recheckSecrets} />
      ) : activeTab === 'workflow-search' ? (
        <WorkflowSearch />
      ) : activeTab === 'ai-analysis' ? (
        <AIWorkflowAnalysis />
      ) : activeTab === 'templates' ? (
        <TemplatesManager />
      ) : activeTab === 'legacy-cleanup' ? (
        <LegacyConfigCleanup />
      ) : null}

      {/* Footer with version */}
      <footer className="app-footer">
        <span>GitHub Onboarding & Workflow Migration Tool</span>
        {appVersion && <span className="version">v{appVersion}</span>}
      </footer>
    </div>
  );
}

export default App;