// Hook to check if required secrets are configured
import { useState, useEffect } from 'react';
import { secretsAPI } from './secretsAPI';

export const useRequiredSecrets = () => {
  const [secretsStatus, setSecretsStatus] = useState({
    loading: true,
    hasGitHubToken: false,
    allConfigured: false,
    tokenIsEmpty: false,
    isAutoGenerated: false,
    error: null
  });

  const checkSecrets = async () => {
    try {
      setSecretsStatus(prev => ({ ...prev, loading: true }));
      
      const secrets = await secretsAPI.getSecrets();
      
      const githubToken = secrets.find(s => s.name === 'GITHUB_TOKEN');
      
      const hasGitHubToken = !!githubToken;
      
      // Check if token exists but might be empty (we can't see the value directly, but check description)
      const tokenIsEmpty = githubToken && githubToken.description?.includes('[AUTO-GENERATED]');
      const isAutoGenerated = githubToken?.description?.includes('[AUTO-GENERATED]');
      
      // Consider it configured only if token exists and is not auto-generated (likely empty)
      const allConfigured = hasGitHubToken && !tokenIsEmpty;

      setSecretsStatus({
        loading: false,
        hasGitHubToken,
        allConfigured,
        tokenIsEmpty,
        isAutoGenerated,
        error: null
      });

      return allConfigured;
    } catch (err) {
      setSecretsStatus({
        loading: false,
        hasGitHubToken: false,
        allConfigured: false,
        tokenIsEmpty: false,
        isAutoGenerated: false,
        error: err.message
      });
      return false;
    }
  };

  useEffect(() => {
    checkSecrets();
  }, []);

  return { ...secretsStatus, recheckSecrets: checkSecrets };
};
