name: Black Duck Coverity Static Analysis
description: GitHub workflow template for Coverity static analysis using Black Duck Security Scan Action

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch: 

jobs:
  coverity-scan:
    runs-on: ubuntu-latest
    name: Coverity Static Analysis
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Build Environment
        run: |
          # Add your build dependencies setup here
          # For example:
          # sudo apt-get update
          # sudo apt-get install -y build-essential cmake
          
      - name: Coverity Security Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          
          ### PROJECT CONFIGURATION
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
          
          ### BUILD COMMANDS (customize for your project)
          # coverity_build_command: mvn clean install
          # coverity_clean_command: mvn clean
          
          ### POLICY ENFORCEMENT: Uncomment to break build on policy violations
          # coverity_policy_view: 'Outstanding Issues'
          
          ### PULL REQUEST COMMENTS: Enable automatic PR comments for new issues
          coverity_prComment_enabled: true
          ## Filter comments by impact level (optional)
          # coverity_prComment_impacts: 'High,Medium,Low,Audit'
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments enabled
          
          ### COVERITY CONNECT USERS: Uncomment if using on-premises Coverity
          # coverity_local: true
          
          ### ADVANCED CONFIGURATION (optional)
          # coverity_waitForScan: true  # Wait for scan completion
          # coverity_config_path: /path/to/coverity.yml
          # coverity_args: --verbose
          
          ### PROJECT DIRECTORY (optional)
          # project_directory: ${{ vars.PROJECT_DIRECTORY }}
          
      - name: Save Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverity-logs
          path: ${{ github.workspace }}/.bridge
          include-hidden-files: true

# Configuration Notes:
# 1. Set COVERITY_URL in repository variables
# 2. Set COVERITY_USER and COVERITY_PASSPHRASE in repository secrets
# 3. Ensure Coverity project and stream exist in your Coverity server
# 4. Customize build commands for your specific project
# 5. For Coverity Connect (on-premises), set coverity_local: true